import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score
data = pd.read_csv("D:\Bangalore_Restaurants.csv")
data1 = pd.read_csv("D:\Pune Restaurants.csv")
common_columns = [
'Restaurant_Name', 'Category', 'Locality', 'Pricing_for_2',
'Dining_Rating', 'Dining_Review_Count', 'Delivery_Rating','Delivery_Rating_Count']
combined_data = pd.merge(data, data1, on=common_columns, how='outer')
corr = combined_data.select_dtypes(include=[np.number]).corr()
plt.figure(figsize=(10, 8))
cmap = sns.diverging_palette(220, 20, as_cmap=True)
sns.heatmap(corr, cmap=cmap, annot=True, fmt=".2f", linewidths=.5, square=True,cbar_kws={"shrink": 0.75})
plt.title('Correlation Heatmap of combined_data')
plt.show()
sns.set(style="whitegrid")
sns.regplot(x='Pricing_for_2', y='Delivery_Rating_Count', data=combined_data, scatter_kws={'alpha': 0.3})
plt.xlabel('Pricing_for_2')
plt.ylabel('Delivery_Rating_Count')
plt.title('Scatter Plot: Pricing_for_2 vs Delivery_Rating_Count')
plt.tight_layout()
plt.show()
sns.regplot(x='Delivery_Rating', y='Pricing_for_2', data=combined_data, scatter_kws={'alpha': 0.3})
plt.xlabel('Delivery_Rating')
plt.ylabel('Pricing_for_2')
plt.title('Scatter Plot: Delivery_Rating vs Pricing_for_2')
plt.tight_layout()
plt.show()
sns.regplot(x='Pricing_for_2', y='Dining_Review_Count', data=combined_data, scatter_kws={'alpha': 0.3})
plt.xlabel('Pricing_for_2')
plt.ylabel('Dining_Review_Count')
plt.title('Scatter Plot: Pricing_for_2 vs Dining_Review_Count')
plt.tight_layout()
plt.show()
sns.regplot(x='Dining_Rating', y='Pricing_for_2', data=combined_data, scatter_kws={'alpha': 0.3})
plt.xlabel('Dining_Rating')
plt.ylabel('Pricing_for_2')
plt.title('Scatter Plot: Dining_Rating vs Pricing_for_2')
plt.tight_layout()
plt.show()
sns.histplot(x='Dining_Review_Count', y='Dining_Rating', data=combined_data)
plt.title("Dining Review Count vs Dining Rating")
plt.tight_layout()
plt.show()
sns.displot(combined_data['Pricing_for_2'], kde=True)
plt.title("Distribution of Pricing_for_2")
plt.tight_layout()
plt.show()
sns.displot(combined_data['Delivery_Rating'], kde=True)
plt.title("Distribution of Delivery_Rating")
plt.tight_layout()
plt.show()
sns.displot(combined_data['Dining_Rating'], kde=True)
plt.title("Distribution of Dining_Rating")
plt.tight_layout()
plt.show()
loc_count_c = combined_data['Locality'].value_counts().head(10).sort_values()
no_delivery_restaurants = combined_data[combined_data['Delivery_Rating'].isnull()]
locality_counts_c = no_delivery_restaurants['Locality'].value_counts().head(10).sort_values()
plt.figure(figsize=(35, 10))
plt.barh(loc_count_c.index, loc_count_c.values, color='blue', label='Restaurants in Combined Dataset')
plt.barh(locality_counts_c.index, locality_counts_c.values, color='red', label='No Delivery Option')
plt.xlabel('Number of Restaurants')
plt.ylabel('Locality')
plt.title('Comparison of Restaurants Across Localities')
plt.legend()
plt.tight_layout()
plt.show()
